server:
  port: 8051
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chennianjun/springcloudconfig #配置git地址
          username: ******* #git账号
          password: *******
          search-paths: spring-cloud-config-repo

