server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: microservice-consumer-movie,microservice-consumer-movie-hystrix-stream
  cluster-name-expression: "'default'"